name: &this command-wrapper
version: 0.1.0.0
synopsis: |
  Command wrapper for building modular toolsets with uniform UI
description: |
  Command wrapper for building modular toolsets with uniform UI
github: trskop/command-wrapper
license: BSD3
license-file: LICENSE
author: Peter Trško
maintainer: peter.trsko@gmail.com
copyright: (c) 2014-2019 Peter Trško
category: Tools

extra-source-files:
  - README.md
  - dhall/*.dhall
  - dhall/CommandWrapper/*
  - dhall/CommandWrapper/Type/*

default-extensions:
  - BlockArguments
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators

dependencies:
  - base

  - ansi-terminal
  - bytestring
  - case-insensitive
  - comonad
  - containers
  - dhall >=1.23  # Functioning support of Dhall Standard 7.0.0
  - dhall-bash
  - dhall-json
  - directory
  - endo
  - executable-path
  - file-embed
  - filepath
  - fuzzy
  - generic-lens
  - host-and-port
  - mainplate
  - mtl
  - optparse-applicative
  - prettyprinter
  - prettyprinter-ansi-terminal
  - process
  - safe
  - template-haskell
  - terminal-size
  - terminfo
  - text
  - unix
  - unordered-containers
  - verbosity >=0.3

  # For `config`, may be redesigned:
  - projectroot

  # `config --dhall[-repl]`
  - aeson
  - aeson-pretty
  - cborg
  - cborg-json
# - dotgen
  - serialise
  - transformers

ghc-options: -Wall -Wcompat

library:
  source-dirs: src

executables:
  *this:
    source-dirs: app
    main: Main.hs
    dependencies:
      - *this

  command-wrapper-cd:
    source-dirs: app-cd
    main: Main.hs
    dependencies:
      - *this
      - turtle

  command-wrapper-skel:
    source-dirs: app-skel
    main: Main.hs
    dependencies:
      - *this
      - turtle
      - open-in-editor

  command-wrapper-exec:
    source-dirs: app-exec
    main: Main.hs
    dependencies:
      - *this
      - clock
      - turtle
