name: &this command-wrapper
version: 0.1.0.0
synopsis: |
  Command wrapper for building modular toolsets with uniform UI
description: |
  Command wrapper for building modular toolsets with uniform UI
github: trskop/command-wrapper
license: BSD3
license-file: LICENSE
author: Peter Trško
maintainer: peter.trsko@gmail.com
copyright: (c) 2014-2019 Peter Trško
category: Tools

extra-source-files:
  - README.md
  - dhall/CommandWrapper/*.dhall
  - dhall/CommandWrapper/Type/*.dhall

default-extensions:
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - OverloadedStrings
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - TupleSections
  - TypeApplications

dependencies:
  - base

  - ansi-terminal
  - case-insensitive
  - comonad
  - dhall >=1.20
  - dhall-bash
  - dhall-json
  - directory
  - endo
  - executable-path
  - filepath
  - fuzzy
  - generic-lens
  - host-and-port
  - mainplate
  - mtl
  - optparse-applicative
  - prettyprinter
  - prettyprinter-ansi-terminal
  - safe
  - terminal-size
  - terminfo
  - text
  - unix
  - unordered-containers
  - verbosity >=0.3

ghc-options: -Wall

library:
  source-dirs: src

executables:
  *this:
    source-dirs: app
    main: Main.hs
    dependencies:
      - *this

  command-wrapper-cd:
    source-dirs: app-cd
    main: Main.hs
    dependencies:
      - *this
      - turtle

  command-wrapper-skel:
    source-dirs: app-skel
    main: Main.hs
    dependencies:
      - *this
      - turtle

  command-wrapper-exec:
    source-dirs: app-exec
    main: Main.hs
    dependencies:
      - *this
      - containers

# command-wrapper-daemon:
#   source-dirs: app-daemon
#   main: Main.hs
#   dependencies:
#     - *this
#     - containers
