# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-13.0

packages:
  - '.'
  - location:
      git: https://github.com/trskop/host-and-port.git
      commit: f4639d63f5c2e4c4faef94f5214111625af2a85d
    extra-dep: True
  - location:
      git: https://github.com/trskop/mainplate.git
      commit: adbade9b17185119786b90ed9f539976f89e1d14
    extra-dep: True
  - location:
      git: https://github.com/trskop/verbosity.git
      commit: 2739b6bdf2bc7ed7d8c938d794e96341a37f2d2b
    extra-dep: True

extra-deps:
  - endo-0.3.0.1
  - fuzzy-0.1.0.0

# Keeping the following in case of new Dhall release:
#
# - dhall-1.19.1
# - dhall-bash-1.0.17
# - dhall-json-1.2.5
# - dhall-text-1.0.14

# # Dhall dependencies:
# - dotgen-0.4.2@sha256:309b7cc8a3593a8e48bee7b53020d5f72db156d58edf78a0214f58fbb84b292b
# - serialise-0.2.1.0@sha256:8d6051f64c6ebfaf705195dd0b8dfb667617f2e674b290ed2e44985009e4f951
# - megaparsec-7.0.4
# - repline-0.2.0.0
# - neat-interpolation-0.3.2.4  # dhall-bash

flags:
  verbosity:
    dhall: true

  host-and-port:
    dhall: true
    generic-lens: true
