# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-14.20

packages:
  - '.'

extra-deps:
  - endo-0.3.0.1
  - fuzzy-0.1.0.0
  - lock-file-0.7.0.0
  - verbosity-0.3.0.0
  - prettyprinter-1.5.1

  # Don't forget to upgrade Dhall Standard version in
  # ./src/CommandWrapper/Internal.hs when upgrading Dhall library.
  - dhall-1.29.0
  - dhall-bash-1.0.27
  - dhall-json-1.6.1
  - aeson-yaml-1.0.5.0

# Keeping the following in case of new Dhall release:
  # Dhall dependencies:
# - dotgen-0.4.2@sha256:309b7cc8a3593a8e48bee7b53020d5f72db156d58edf78a0214f58fbb84b292b
# - serialise-0.2.1.0@sha256:8d6051f64c6ebfaf705195dd0b8dfb667617f2e674b290ed2e44985009e4f951
# - megaparsec-7.0.4
# - repline-0.2.0.0
# - neat-interpolation-0.3.2.4  # dhall-bash

  - git: https://github.com/trskop/host-and-port.git
    commit: 67a38bd04c7385542706da7d80822b1a35e76322

  - git: https://github.com/trskop/mainplate.git
    commit: b6ac83b01434031522893bb4906ef4971c3d6e3f

  - git: https://github.com/trskop/open-in-editor.git
    commit: 003e0c7c32628ee27332becfab92b62cad194163

flags:
  verbosity:
    dhall: true

  host-and-port:
    dhall: true
    generic-lens: true

allow-newer: false
