# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

# TODO: Currently fully static build uses old LTS 14.27 due to Docker image
# that we are using. See `Shakefile.hs` for more information.
#
# GHC 8.6.5
#resolver: lts-14.27

# GHC 8.8.4
resolver: lts-16.13

packages:
  - './command-wrapper-core/'
  - './command-wrapper-subcommand/'
  - './command-wrapper-subcommand-shake/'
  - './command-wrapper/'

extra-deps:
  - endo-0.3.0.1
  - fuzzy-0.1.0.0
  - lock-file-0.7.0.0
  - verbosity-0.4.0.0
  - prettyprinter-1.7.0

  # Don't forget to upgrade Dhall Standard version in
  # ./src/CommandWrapper/Internal.hs when upgrading Dhall library.
  - dhall-1.34.0
  - dhall-bash-1.0.32
  - dhall-json-1.7.1
  - aeson-yaml-1.1.0.0
  - repline-0.4.0.0
  - haskeline-0.8.1.0

# Keeping the following in case of new Dhall release:
  # Dhall dependencies:
# - dotgen-0.4.2@sha256:309b7cc8a3593a8e48bee7b53020d5f72db156d58edf78a0214f58fbb84b292b
# - serialise-0.2.1.0@sha256:8d6051f64c6ebfaf705195dd0b8dfb667617f2e674b290ed2e44985009e4f951
# - megaparsec-7.0.4
# - repline-0.2.0.0
# - neat-interpolation-0.3.2.4  # dhall-bash

  - git: https://github.com/trskop/host-and-port.git
    commit: f0ac77ce78887dbce9a140cf39ea6af801dd2438

  - git: https://github.com/trskop/mainplate.git
    commit: 6ed414df4a5f649a2b773f12487de79792a9861c

  - git: https://github.com/trskop/open-in-editor.git
    commit: b8db3c09e1e05d4b61fa028c8d1a3ee8dc4b4ba8

flags:
  verbosity:
    dhall: true

  host-and-port:
    dhall: true
    generic-lens: true

allow-newer: false
