# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-12.14

packages:
  - '.'
  - location:
      git: https://github.com/trskop/host-and-port.git
      commit: f8a9f1ae1a410ad12969f9c5ea0810de45d9b2bc
    extra-dep: True
  - location:
      git: https://github.com/trskop/mainplate.git
      commit: f70d6cea0a01df90715affcfa733227f48b184f1
    extra-dep: True
  - location:
      git: https://github.com/trskop/verbosity.git
      commit: 2739b6bdf2bc7ed7d8c938d794e96341a37f2d2b
    extra-dep: True

extra-deps:
  - endo-0.3.0.1
  - dhall-1.18.0
  - dhall-bash-1.0.16
  - dhall-json-1.2.4
  - dhall-text-1.0.13

  # Dhall dependencies:
  - serialise-0.2.1.0
  - megaparsec-7.0.2
  - repline-0.2.0.0
  - neat-interpolation-0.3.2.4  # dhall-bash

flags:
  verbosity:
    dhall: True
