# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-12.7

packages:
  - '.'
  - location:
      git: https://github.com/trskop/host-and-port.git
      commit: 290fd24f59aaaaf0811aa1b61aece3ac6b1dc62e
    extra-dep: True
  - location:
      git: https://github.com/trskop/mainplate.git
      commit: b41eed947ed02cfadf85667fd846f3a5bfe82e77
    extra-dep: True
  - location:
      git: https://github.com/trskop/verbosity.git
      commit: 5e3f323a630978d511526e5f871e2bfbd37892dd
    extra-dep: True

extra-deps:
  - endo-0.3.0.1
  - dhall-1.16.1

flags:
  verbosity:
    dhall: True
