# For advanced use and comprehensive documentation of the format, please see:
# https://docs.haskellstack.org/en/stable/yaml_configuration/

resolver: lts-13.18

packages:
  - '.'
  - location:
      git: https://github.com/trskop/host-and-port.git
      commit: f4639d63f5c2e4c4faef94f5214111625af2a85d
    extra-dep: True
  - location:
      git: https://github.com/trskop/mainplate.git
      commit: 34bc37da5bf31fd158aeda28d3297fc7e0062ce8
    extra-dep: True

extra-deps:
  - endo-0.3.0.1
  - fuzzy-0.1.0.0
  - verbosity-0.3.0.0

  - dhall-1.22.0
  - dhall-bash-1.0.20
  - dhall-json-1.2.8
  - dhall-text-1.0.17

# Keeping the following in case of new Dhall release:
  # Dhall dependencies:
# - dotgen-0.4.2@sha256:309b7cc8a3593a8e48bee7b53020d5f72db156d58edf78a0214f58fbb84b292b
# - serialise-0.2.1.0@sha256:8d6051f64c6ebfaf705195dd0b8dfb667617f2e674b290ed2e44985009e4f951
# - megaparsec-7.0.4
# - repline-0.2.0.0
# - neat-interpolation-0.3.2.4  # dhall-bash

flags:
  verbosity:
    dhall: true

  host-and-port:
    dhall: true
    generic-lens: true
