name: &this command-wrapper
version: 0.1.0.0
synopsis: |
  Command wrapper for building modular toolsets with uniform UI
description: |
  Command wrapper for building modular toolsets with uniform UI

  See [GitHub README](https://github.com/trskop/command-wrapper#readme) for
  more information.

github: trskop/command-wrapper
license: BSD3
license-file: LICENSE
author: Peter Trško
maintainer: peter.trsko@gmail.com
copyright: (c) 2014-2020 Peter Trško
category: Tools

flags:
  static:
    description: Build static executables
    manual: true
    default: false

  nix:
    description: Nix-specific tweaks for executables
    manual: true
    default: false

extra-source-files:
  - README.md
  - bash/*
  - dhall/*
  - dhall/**/*
  - man/*.md
  - nix/**/*.dhall
  - nix/**/*.nix
  - nix/README.md

default-extensions:
  - BlockArguments
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators

dependencies:
  - command-wrapper-core

  - base >=4.12 && <5
  # ^ Version 4.12.0.0 is bundled with 8.6.*, we support GHC 8.6.5 for static
  # build.

  - aeson
  - aeson-pretty
  - ansi-terminal
  - atomic-write >=0.2.0.0
  - bytestring
  - case-insensitive
  - cborg
  - cborg-json
  - comonad
  - containers
  - cryptonite
  - dhall >=1.33.1
  # ^ Dhall Standard 17.0.0; deprecated Optional/fold; introduced Expector.
  - dhall-bash >=1.0.29
  # ^ First version supporting dhall-1.31.
# - dhall-json >=1.6.3
  # ^ First version supporting dhall-1.31.
  - directory
  - either
  - endo >=0.3.0.1
  - executable-path
  - file-embed
  - filepath
  - fuzzy
  - generic-lens
  - host-and-port
  - lock-file >=0.7.0.0
  - mainplate
  - mtl
  - open-in-editor
  - optparse-applicative
  - prettyprinter
  - prettyprinter-ansi-terminal
  - process
  - safe
  - serialise
  - template-haskell
  - temporary
  - terminal-size
  - terminfo
  - text
  - transformers
  - unix
  - unordered-containers
  - verbosity >=0.3
  - vty

ghc-options: ["-Wall", "-Wcompat"]

library:
  source-dirs: src

  when:
    - condition: flag(static)
      ghc-options:
        - -static
        - -O2
        - -fPIC

executables:
  *this:
    source-dirs: app
    main: Main.hs
    dependencies:
      - *this
    ghc-options: ["-threaded"]

    when:
      - condition: flag(static)
        ghc-options:
          - -static
          - -O2
          - -fPIC
        cpp-options:
          - -DSTATIC_EXECUTABLE
        cc-options:
          - -static
        ld-options:
          - -static
          - -pthread

      - condition: flag(nix)
        cpp-options:
          - -DNIX_EXECUTABLE

  command-wrapper-cd:
    source-dirs: app-cd
    main: Main.hs
    dependencies:
      - *this
      - command-wrapper-subcommand

      - turtle
      - shell-escape
    ghc-options: ["-threaded"]

    when:
      - condition: flag(static)
        ghc-options:
          - -static
          - -O2
          - -fPIC
        cc-options:
          - -static
        ld-options:
          - -static
          - -pthread

  command-wrapper-skel:
    source-dirs: app-skel
    main: Main.hs
    dependencies:
      - *this
      - command-wrapper-subcommand

      - turtle
    ghc-options: ["-threaded"]

    when:
      - condition: flag(static)
        ghc-options:
          - -static
          - -O2
          - -fPIC
        cc-options:
          - -static
        ld-options:
          - -static
          - -pthread

  command-wrapper-exec:
    source-dirs: app-exec
    main: Main.hs
    dependencies:
      - *this
      - command-wrapper-subcommand

      - clock
      - turtle
    ghc-options: ["-threaded"]

    when:
      - condition: flag(static)
        ghc-options:
          - -threaded
          - -static
          - -O2
          - -fPIC
        cc-options:
          - -static
        ld-options:
          - -static
          - -pthread

tests:
  command-wrapper-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
      - *this

      - Glob >=0.10.0 && <1
      - call-stack
      - deepseq
      - tasty
      - tasty-hunit
      - tasty-program
    ghc-options: ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
