name: &this command-wrapper-core
version: 0.1.0.0
synopsis: |
  Command wrapper for building modular toolsets with uniform UI: Core library
description: |
  Command wrapper for building modular toolsets with uniform UI: Core library

  See [GitHub README](https://github.com/trskop/command-wrapper#readme) for
  more information.

github: trskop/command-wrapper
license: BSD3
license-file: LICENSE
author: Peter Trško
maintainer: peter.trsko@gmail.com
copyright: (c) 2014-2020 Peter Trško
category: Tools

flags:
  static:
    description: Build static executables
    manual: true
    default: false

extra-source-files:
  - README.md

default-extensions:
  - BlockArguments
  - DefaultSignatures
  - DeriveAnyClass
  - DeriveFunctor
  - DeriveGeneric
  - DerivingStrategies
  - DuplicateRecordFields
  - FlexibleContexts
  - FlexibleInstances
  - GeneralizedNewtypeDeriving
  - InstanceSigs
  - LambdaCase
  - MultiWayIf
  - NamedFieldPuns
  - NoImplicitPrelude
  - OverloadedStrings
  - PatternSynonyms
  - RankNTypes
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TupleSections
  - TypeApplications
  - TypeFamilies
  - TypeOperators

dependencies:
  - base >=4.12 && <5
  # ^ Version 4.12.0.0 is bundled with 8.6.*, we support GHC 8.6.5 for static
  # build.

  - ansi-terminal
  - atomic-write >=0.2.0.0
  - bytestring
  - case-insensitive
  - comonad
  - dhall >=1.33.1
  # ^ Dhall Standard 17.0.0; deprecated Optional/fold; introduced Expector.
  - directory
  - either
  - executable-path
  - filepath
  - generic-lens
  - mainplate
  - mtl
  - optparse-applicative
  - prettyprinter
  - prettyprinter-ansi-terminal
  - terminal-size
  - terminfo
  - text
  - unordered-containers
  - verbosity >=0.3

ghc-options: ["-Wall", "-Wcompat"]

library:
  source-dirs: src

  when:
    - condition: flag(static)
      ghc-options:
        - -static
        - -O2
        - -fPIC

tests:
  command-wrapper-core-tests:
    source-dirs: test
    main: Main.hs
    dependencies:
      - *this

      - call-stack
      - deepseq
      - tasty
      - tasty-hunit
#     - tasty-program
    ghc-options: ["-threaded", "-rtsopts", "-with-rtsopts=-N"]
